### ISSUE TITLE
About the reference paper

### ISSUE THREAD

**Issue by Gavin-Lijy** [kundajelab/neural_motif_discovery#1]
Hi, I haven't found the paper you mentioned. Has it been published yet?

**Comment by akundaje** [comment]
No. We expect to release the preprint in a month or so.

**Comment by Gavin-Lijy** [comment]
Thank you so much for your such quick reply, and the tremendous contribution your group has made to the community! I'm looking into potential model explainers besides TF-MoDISco as I prepare to modify ChromDragoNN to decipher the **TF regulatory networks**. Looking forward to reading your new preprint and discussing with you when we find or develop good methods for our task!

**Comment by akundaje** [comment]
This paper uses TF-MODISCO btw. And we have a more efficient implementation
of Modisco now. It's linked at the MODISCO GitHub.
